language: java

before_install:
  – ./gradlew build

jdk:
  - oraclejdk11

script:
  - sonar-scanner

deploy:
  provider: heroku
  api_key: f544488b-9a79-460f-a9bf-ed3c348ff870
  skip_cleanup: true

addons:
  sonarcloud:
    organization: "arturarede"
    token: 5c67909bc9dac35fcaba891b436a874a91d2c122