language: java

before_install:
  – chmod +x gradlew

jdk:
  - oraclejdk11

addons:
  sonarcloud:
    organization: "arturarede"
    token:
      secure: "YgTMGXrE7bKrK9kgG5Fuzy6ipfiai231CZ+1wq5gbf2eeNrfLHbRPJ/zL0xHbbLA3gFf2Z1sYz378s+kELRZVw+2UFH5rAUp4yu1hKStFzRQKnSNETzAZyRI6MDartYM1nn3IXikI4mYuKs8AqKy4POEQQQb1yLxu1hsKNMAA5a/dJzIaGL59cA0cxkRAsp08rBPAnsnZ0u/qOZI4OCssAlcqKUDzFx1EWjxXbZx45iE1i17JcrH1Y7PX2kCKMsLaPz13m0NbPAfqBLtJSZ5FNGwLS7xD3xo01bbMG8lH29E77KTAx26KHeIAfA+AntwItVuz0K0JwsC5QV2WaU3GiPP3ZQXDk1MUjzBIHxH6NZ4khfSpzbxhRAGjUTV/SbNozu1LNEWGUSqLQdGFZjKDudO77ELUp6c1PRfFlvjMuOet28fLFG/e0yieOXbkXIXHJokMAxqjdRPkCLV0a2z/4mSj/qCGbw0JIbWjQ1x4aDwZbLhazEK+ZV6UP0gLEyl9uBzhvdgJG+c2V1bvG/ri7t/Szv5bFyapT1we0/fGJIE/PxJDwyFTx5JG6Yfxpe/eZcmGhqDQlaq5dmObeLajifhRMk3yI0n/w3bXBYL/5s9P7Q45iyfFjOWIp5QKuggqP/guh6mbzNBPAXyRVAPwwAnL51gD/rVBFEgC2WJ3r0="

script:
  - sonar-scanner