language: java

before_install:
  – chmod +x gradlew

jdk:
  - oraclejdk11

addons:
  sonarcloud:
    organization: "arturarede"
    token:
      secure: 5c67909bc9dac35fcaba891b436a874a91d2c122
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner